/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsNumber,
  ValidateNested,
} from "class-validator";
import { TaskCreateNestedManyWithoutFilesInput } from "./TaskCreateNestedManyWithoutFilesInput";
import { Type } from "class-transformer";
import { UserCreateNestedManyWithoutFilesInput } from "./UserCreateNestedManyWithoutFilesInput";

@InputType()
class FileCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  path?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  size?: number | null;

  @ApiProperty({
    required: false,
    type: () => TaskCreateNestedManyWithoutFilesInput,
  })
  @ValidateNested()
  @Type(() => TaskCreateNestedManyWithoutFilesInput)
  @IsOptional()
  @Field(() => TaskCreateNestedManyWithoutFilesInput, {
    nullable: true,
  })
  tasks?: TaskCreateNestedManyWithoutFilesInput;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutFilesInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutFilesInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutFilesInput, {
    nullable: true,
  })
  users?: UserCreateNestedManyWithoutFilesInput;
}

export { FileCreateInput };
